// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/18/2025, 7:23:14 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/project/sandbox/user-workspace/vidaplus-sghss/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/project/sandbox/user-workspace/vidaplus-sghss/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/project/sandbox/user-workspace/vidaplus-sghss/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/project/sandbox/user-workspace/vidaplus-sghss/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/project/sandbox/user-workspace/vidaplus-sghss/plugins/**/*.{js,ts,mjs}","/project/sandbox/user-workspace/vidaplus-sghss/composables/**/*.{js,ts,mjs}","/project/sandbox/user-workspace/vidaplus-sghss/utils/**/*.{js,ts,mjs}","/project/sandbox/user-workspace/vidaplus-sghss/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/project/sandbox/user-workspace/vidaplus-sghss/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/project/sandbox/user-workspace/vidaplus-sghss/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/project/sandbox/user-workspace/vidaplus-sghss/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;